---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: matthewschuchard/vault-api
    resource_class: small
    steps:
    - checkout
    - run:
        name: install prereqs
        command: apk add --no-cache --update make
    - run:
        name: build
        command: make build
    - run:
        name: bootstrap vault server
        command: make bootstrap
    - run:
        name: unit test
        command: make unit

workflows:
  execute_tests:
    jobs:
    - test
