---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: golang:1.21-alpine
    resource_class: small
    steps:
    - checkout
    - run:
        name: build
        command: go build -v ./...
    - run:
        name: unit test
        command: go test -v ./...

workflows:
  execute_tests:
    jobs:
    - test
