---
name: test build

on:
  push:
    branches: [master]
    paths:
    - '**.go'
    - 'go.mod'
  pull_request:
    branches: [master]
    paths:
    - '**.go'
    - 'go.mod'

jobs:
  go-build:
    runs-on: ubuntu-latest
    container: matthewschuchard/vault-api
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install prereqs
      run: apk add --no-cache --update build-base
    - name: build
      run: make build
    - name: bootstrap vault server
      run: make bootstrap
    - name: unit test
      run: make unit
