---
name: test build

on:
  push:
    branches: [master]
    paths:
    - '**.go'
    - 'go.mod'
  pull_request:
    branches: [master]
    paths:
    - '**.go'
    - 'go.mod'

jobs:
  go-build:
    runs-on: ubuntu-22.04
    container: golang:1.21-alpine
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: go build -v ./...
    - name: unit test
      run: go test -v ./...
