---
name: release
on:
  push:
    tags:
    - 'v*'

jobs:
  goreleaser:
    name: create and publish vault-raft-backup release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: unshallow
      run: git fetch --prune --unshallow
    - name: set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
